### ISSUE TITLE
npm run serve ，在浏览器访问页面空白，提示BASE_URL

### ISSUE THREAD

**Issue by qbob** [youzan/vant-demo#18]
DONE  Compiled successfully in 3835ms                                                                                             11:10:25

  App running at:
  - Local:   http://localhost:8080/https://youzan.github.io/vant-demo/
  - Network: http://192.168.0.103:8080/https://youzan.github.io/vant-demo/

URIError: Failed to decode param '/%3C%=%20BASE_URL%20%%3Efavicon.ico'
    at decodeURIComponent (<anonymous>)
    at decode_param (/www/testvue/vant-demo/node_modules/express/lib/router/layer.js:172:12)
    at Layer.match (/www/testvue/vant-demo/node_modules/express/lib/router/layer.js:123:27)
    at matchLayer (/www/testvue/vant-demo/node_modules/express/lib/router/index.js:574:18)
    at next (/www/testvue/vant-demo/node_modules/express/lib/router/index.js:220:15)
    at expressInit (/www/testvue/vant-demo/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/www/testvue/vant-demo/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/www/testvue/vant-demo/node_modules/express/lib/router/index.js:317:13)
    at /www/testvue/vant-demo/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/www/testvue/vant-demo/node_modules/express/lib/router/index.js:335:12)
    at next (/www/testvue/vant-demo/node_modules/express/lib/router/index.js:275:10)
    at query (/www/testvue/vant-demo/node_modules/express/lib/middleware/query.js:45:5)
    at Layer.handle [as handle_request] (/www/testvue/vant-demo/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/www/testvue/vant-demo/node_modules/express/lib/router/index.js:317:13)
    at /www/testvue/vant-demo/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/www/testvue/vant-demo/node_modules/express/lib/router/index.js:335:12)

**Comment by zhaofangfangzff** [comment]
遇到了同样的情况

**Comment by dharmatv** [comment]
i am also getting same error, finally i resolved my issue 

in my case i was change baseURL:'https://something.com' to baseURL:'' in vue.config.js

**Comment by cloveropen** [comment]
用 publicPath: '/'    替换baseUrl: '/' 试一下
