### ISSUE TITLE
vant-demo nuxt3无法正常运行在生产环境

### ISSUE THREAD

**Issue by powerlau** [youzan/vant-demo#97]
执行yarn dev 可以正常运行在开发环境页面也显示正常，运行yarn dev & yarn start 虽然不会报错，但是打开网页终端会显示如下错误，且页面显示不正常。
![image](https://user-images.githubusercontent.com/7065910/148498298-ff6b69cf-d049-42ee-8dfb-58ae9c930c58.png)

Listening on http://localhost:3000
TypeError: Cannot read properties of null (reading 'proxy')
    at setup (D:\dev\codes\nuxt3\.output\server\node_modules\vant\lib\image\Image.js:47:39)
    at callWithErrorHandling (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:7189:22)
    at setupStatefulComponent (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:6905:29)
    at setupComponent (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:6886:11)
    at renderComponentVNode (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9795:17)
    at Object.ssrRenderComponent (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:10220:12)
    at _sfc_ssrRender (file:///D:/dev/codes/nuxt3/.output/server/chunks/server.mjs:3437:32)
    at renderComponentSubTree (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9860:13)
    at renderComponentVNode (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9811:16)
    at Object.ssrRenderComponent (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:10220:12)
[Vue warn]: Component van-image  is missing template or render function.
[Vue warn]: provide() can only be used inside setup().
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: inject() can only be used inside setup() or functional components.
TypeError: Cannot read properties of null (reading 'proxy')
    at useRoute (D:\dev\codes\nuxt3\.output\server\node_modules\vant\lib\composables\use-route.js:36:42)
    at setup (D:\dev\codes\nuxt3\.output\server\node_modules\vant\lib\cell\Cell.js:50:40)
    at callWithErrorHandling (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:7189:22)
    at setupStatefulComponent (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:6905:29)
    at setupComponent (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:6886:11)
    at renderComponentVNode (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9795:17)
    at renderVNode (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9901:22)
    at renderVNodeChildren (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9916:9)
    at renderVNode (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9893:13)
    at renderVNodeChildren (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9916:9)
[Vue warn]: Component van-cell  is missing template or render function.
TypeError: Cannot read properties of null (reading 'proxy')
    at useRoute (D:\dev\codes\nuxt3\.output\server\node_modules\vant\lib\composables\use-route.js:36:42)
    at setup (D:\dev\codes\nuxt3\.output\server\node_modules\vant\lib\cell\Cell.js:50:40)
    at callWithErrorHandling (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:7189:22)
    at setupStatefulComponent (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:6905:29)
    at setupComponent (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:6886:11)
    at renderComponentVNode (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9795:17)
    at renderVNode (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9901:22)
    at renderVNodeChildren (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9916:9)
    at renderVNode (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9893:13)
    at renderVNodeChildren (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9916:9)
[Vue warn]: Component van-cell  is missing template or render function.
TypeError: Cannot read properties of null (reading 'proxy')
    at useRoute (D:\dev\codes\nuxt3\.output\server\node_modules\vant\lib\composables\use-route.js:36:42)
    at setup (D:\dev\codes\nuxt3\.output\server\node_modules\vant\lib\cell\Cell.js:50:40)
    at callWithErrorHandling (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:7189:22)
    at setupStatefulComponent (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:6905:29)
    at setupComponent (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:6886:11)
    at renderComponentVNode (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9795:17)
    at renderVNode (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9901:22)
    at renderVNodeChildren (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9916:9)
    at renderVNode (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9893:13)
    at renderVNodeChildren (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9916:9)
[Vue warn]: Component van-cell  is missing template or render function.
TypeError: Cannot read properties of null (reading 'proxy')
    at useRoute (D:\dev\codes\nuxt3\.output\server\node_modules\vant\lib\composables\use-route.js:36:42)
    at setup (D:\dev\codes\nuxt3\.output\server\node_modules\vant\lib\cell\Cell.js:50:40)
    at callWithErrorHandling (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:7189:22)
    at setupStatefulComponent (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:6905:29)
    at setupComponent (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:6886:11)
    at renderComponentVNode (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9795:17)
    at renderVNode (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9901:22)
    at renderVNodeChildren (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9916:9)
    at renderVNode (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9893:13)
    at renderVNodeChildren (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9916:9)
[Vue warn]: Component van-cell  is missing template or render function.
TypeError: Cannot read properties of null (reading 'proxy')
    at setup (D:\dev\codes\nuxt3\.output\server\node_modules\vant\lib\image\Image.js:47:39)
    at callWithErrorHandling (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:7189:22)
    at setupStatefulComponent (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:6905:29)
    at setupComponent (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:6886:11)
    at renderComponentVNode (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9795:17)
    at Object.ssrRenderComponent (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:10220:12)
    at _sfc_ssrRender (file:///D:/dev/codes/nuxt3/.output/server/chunks/server.mjs:3437:32)
    at renderComponentSubTree (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9860:13)
    at renderComponentVNode (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9811:16)
    at Object.ssrRenderComponent (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:10220:12)
[Vue warn]: Component van-image  is missing template or render function.
[Vue warn]: provide() can only be used inside setup().
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: inject() can only be used inside setup() or functional components.
TypeError: Cannot read properties of null (reading 'proxy')
    at useRoute (D:\dev\codes\nuxt3\.output\server\node_modules\vant\lib\composables\use-route.js:36:42)
    at setup (D:\dev\codes\nuxt3\.output\server\node_modules\vant\lib\cell\Cell.js:50:40)
    at callWithErrorHandling (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:7189:22)
    at setupStatefulComponent (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:6905:29)
    at setupComponent (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:6886:11)
    at renderComponentVNode (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9795:17)
    at renderVNode (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9901:22)
    at renderVNodeChildren (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9916:9)
    at renderVNode (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9893:13)
    at renderVNodeChildren (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9916:9)
[Vue warn]: Component van-cell  is missing template or render function.
TypeError: Cannot read properties of null (reading 'proxy')
    at useRoute (D:\dev\codes\nuxt3\.output\server\node_modules\vant\lib\composables\use-route.js:36:42)
    at setup (D:\dev\codes\nuxt3\.output\server\node_modules\vant\lib\cell\Cell.js:50:40)
    at callWithErrorHandling (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:7189:22)
    at setupStatefulComponent (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:6905:29)
    at setupComponent (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:6886:11)
    at renderComponentVNode (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9795:17)
    at renderVNode (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9901:22)
    at renderVNodeChildren (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9916:9)
    at renderVNode (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9893:13)
    at renderVNodeChildren (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9916:9)
[Vue warn]: Component van-cell  is missing template or render function.
TypeError: Cannot read properties of null (reading 'proxy')
    at useRoute (D:\dev\codes\nuxt3\.output\server\node_modules\vant\lib\composables\use-route.js:36:42)
    at setup (D:\dev\codes\nuxt3\.output\server\node_modules\vant\lib\cell\Cell.js:50:40)
    at callWithErrorHandling (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:7189:22)
    at setupStatefulComponent (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:6905:29)
    at setupComponent (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:6886:11)
    at renderComponentVNode (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9795:17)
    at renderVNode (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9901:22)
    at renderVNodeChildren (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9916:9)
    at renderVNode (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9893:13)
    at renderVNodeChildren (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9916:9)
[Vue warn]: Component van-cell  is missing template or render function.
TypeError: Cannot read properties of null (reading 'proxy')
    at useRoute (D:\dev\codes\nuxt3\.output\server\node_modules\vant\lib\composables\use-route.js:36:42)
    at setup (D:\dev\codes\nuxt3\.output\server\node_modules\vant\lib\cell\Cell.js:50:40)
    at callWithErrorHandling (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:7189:22)
    at setupStatefulComponent (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:6905:29)
    at setupComponent (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:6886:11)
    at renderComponentVNode (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9795:17)
    at renderVNode (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9901:22)
    at renderVNodeChildren (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9916:9)
    at renderVNode (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9893:13)

    at renderVNodeChildren (file:///D:/dev/codes/nuxt3/.output/server/chunks/index.mjs:9916:9)
[Vue warn]: Component van-cell  is missing template or render function.

**Comment by leosin** [comment]
![image](https://user-images.githubusercontent.com/3676670/172851207-0622b412-9e81-4fb4-8133-e2276352d562.png)

我这个打包generate的时候出的错，dev时候没问题
